import { z } from "zod";
import { ContinuitySourceReferenceSchema } from "./continuity";
import { ChangeSetSchema } from "./change-management";

export const AssetTypeSchema=z.enum(["character_card","character_template","lorebook_entry","lorebook_collection","world_setting","location","organization","item","ability_system","magic_system","technology_system","relationship_template","character_arc_template","plot_structure","chapter_template","scene_template","style_profile","language_constraint_set","character_voice_profile","analysis_preset","export_preset","prompt_template","project_template"]);
export const AssetVersionSchema=z.object({versionId:z.string(),assetId:z.string(),versionNumber:z.number().int().positive(),content:z.unknown(),contentSchemaVersion:z.number().int().positive().default(1),parentVersionId:z.string().nullable().default(null),changeSummary:z.string().default(""),sourceReferences:z.array(ContinuitySourceReferenceSchema).default([]),dependencyIds:z.array(z.string()).default([]),createdAt:z.string(),createdBy:z.string().default("user"),status:z.enum(["draft","active","deprecated","archived","invalid"]).default("active")});
export const LibraryAssetSchema=z.object({assetId:z.string(),workspaceId:z.string(),type:AssetTypeSchema,name:z.string(),description:z.string().default(""),tags:z.array(z.string()).default([]),genre:z.string().default(""),themes:z.array(z.string()).default([]),language:z.string().default("zh-CN"),scope:z.enum(["workspace","local","project_private"]).default("workspace"),currentVersionId:z.string(),sourceProjectId:z.string().nullable().default(null),sourceObjectType:z.string().default(""),sourceObjectId:z.string().default(""),sourceReferences:z.array(ContinuitySourceReferenceSchema).default([]),versions:z.array(AssetVersionSchema),createdAt:z.string(),updatedAt:z.string(),archived:z.boolean().default(false),userNotes:z.string().default("")});
export const ProjectAssetLinkSchema=z.object({linkId:z.string(),projectId:z.string(),assetId:z.string(),sourceVersionId:z.string(),mode:z.enum(["copy","reference","derived","template_instance"]),targetType:z.string(),targetId:z.string(),localOverrides:z.record(z.string(),z.unknown()).default({}),localVersion:z.number().int().positive().default(1),status:z.enum(["current","update_available","locally_modified","conflict","source_missing","disconnected","ignored_update"]).default("current"),pinned:z.boolean().default(false),lastCheckedAt:z.string(),lastAppliedVersionId:z.string(),createdAt:z.string(),updatedAt:z.string()});
export const AssetDependencySchema=z.object({dependencyId:z.string(),assetId:z.string(),dependencyAssetId:z.string(),requiredVersionRange:z.string().default("*"),optional:z.boolean().default(false),purpose:z.string().default(""),status:z.enum(["resolved","missing","incompatible","cycle","deprecated"]).default("resolved")});
export const TemplateInstantiationPlanSchema=z.object({planId:z.string(),templateAssetId:z.string(),templateVersionId:z.string(),projectName:z.string(),preview:z.unknown(),operations:z.array(z.object({assetId:z.string(),mode:z.enum(["copy","reference","derived"])})).default([]),warnings:z.array(z.string()).default([]),confirmed:z.boolean().default(false),createdAt:z.string()});
export const AssetPackSchema=z.object({schemaVersion:z.literal(1),manifest:z.object({name:z.string(),createdAt:z.string(),assetCount:z.number().int().nonnegative()}),assets:z.array(LibraryAssetSchema),dependencies:z.array(AssetDependencySchema),checksum:z.string()});
export const AssetLibraryStateSchema=z.object({dataVersion:z.literal(1).default(1),assets:z.array(LibraryAssetSchema).default([]),links:z.array(ProjectAssetLinkSchema).default([]),dependencies:z.array(AssetDependencySchema).default([]),templatePlans:z.array(TemplateInstantiationPlanSchema).default([])}).default({dataVersion:1,assets:[],links:[],dependencies:[],templatePlans:[]});
export const AssetUpdateProposalSchema=z.object({proposalId:z.string(),linkId:z.string(),status:z.enum(["update_available","conflict","source_missing","current"]),baseContent:z.unknown(),upstreamContent:z.unknown(),localOverrides:z.record(z.string(),z.unknown()),changeSet:ChangeSetSchema,applied:z.literal(false)});
export type AssetLibraryState=z.infer<typeof AssetLibraryStateSchema>; export type AssetType=z.infer<typeof AssetTypeSchema>;
