import { z } from "zod";
import { createStableId } from "./lorebook";
export const PLANNING_DATA_VERSION=1; export const PLANNING_PROMPT_VERSION="planning-v1.0.0";
export const ContentStatusSchema=z.enum(["locked","confirmed","draft","suggested","deprecated","unknown"]);
export const PlanningSourceReferenceSchema=z.object({sourceType:z.enum(["user_idea","character_card","lorebook","analysis_report","existing_plan","user_constraint","model_suggestion"]),sourceId:z.string(),sourceName:z.string(),field:z.string(),excerpt:z.string(),version:z.string(),valid:z.boolean().default(true),classification:z.enum(["confirmed_fact","source_setting","user_assumption","model_inference","model_suggestion","unknown"]).default("source_setting"),inference:z.boolean().default(false)});
const BaseShape={id:z.string().min(1),dataVersion:z.literal(PLANNING_DATA_VERSION).default(PLANNING_DATA_VERSION),status:ContentStatusSchema.default("draft"),sources:z.array(PlanningSourceReferenceSchema).default([]),createdAt:z.string(),modifiedAt:z.string()};
const Base=z.object(BaseShape);
export const CreativeConstraintSchema=Base.extend({type:z.enum(["immutable","forbidden","required","preference"]).default("preference"),content:z.string().default(""),locked:z.boolean().default(false)});
export const StoryBibleSchema=Base.extend({projectName:z.string().default(""),logline:z.string().default(""),synopsis:z.string().default(""),genre:z.array(z.string()).default([]),tone:z.array(z.string()).default([]),themes:z.array(z.string()).default([]),corePremise:z.string().default(""),narrativePerspective:z.string().default(""),timeRange:z.string().default(""),mainLocations:z.array(z.string()).default([]),worldRulesSummary:z.string().default(""),coreConflict:z.string().default(""),protagonistGoal:z.string().default(""),opposingForces:z.array(z.string()).default([]),stakes:z.string().default(""),costs:z.string().default(""),endingDirection:z.string().default(""),immutableConditions:z.array(z.string()).default([]),forbiddenDirections:z.array(z.string()).default([]),unresolvedQuestions:z.array(z.string()).default([]),lockedFields:z.array(z.string()).default([]),constraints:z.array(CreativeConstraintSchema).default([])});
export const CharacterStateChangeSchema=Base.extend({characterId:z.string(),characterName:z.string(),before:z.string().default(""),after:z.string().default(""),reason:z.string().default(""),isPublic:z.boolean().default(true)});
export const RelationshipStateChangeSchema=Base.extend({characterIds:z.array(z.string()).min(2),before:z.string().default(""),after:z.string().default(""),trigger:z.string().default(""),aftermath:z.string().default("")});
export const WorldStateChangeSchema=Base.extend({entity:z.string(),before:z.string().default(""),after:z.string().default(""),reason:z.string().default(""),scope:z.string().default("")});
export const PlotDependencySchema=Base.extend({fromBeatId:z.string(),toBeatId:z.string(),type:z.enum(["causes","enables","motivates","reveals","prevents","complicates","resolves","foreshadows","contradicts"]),description:z.string().default("")});
export const PlotBeatSchema=Base.extend({title:z.string().default("未命名节点"),sectionId:z.string().default(""),summary:z.string().default(""),purpose:z.string().default(""),characterIds:z.array(z.string()).default([]),location:z.string().default(""),prerequisites:z.array(z.string()).default([]),trigger:z.string().default(""),mainAction:z.string().default(""),directResult:z.string().default(""),longTermConsequences:z.array(z.string()).default([]),risksAndCosts:z.string().default(""),characterChanges:z.array(CharacterStateChangeSchema).default([]),relationshipChanges:z.array(RelationshipStateChangeSchema).default([]),worldChanges:z.array(WorldStateChangeSchema).default([]),newInformation:z.array(z.string()).default([]),hiddenInformation:z.array(z.string()).default([]),dependencies:z.array(PlotDependencySchema).default([]),locked:z.boolean().default(false),newSettingMarked:z.boolean().default(false)});
export const PlotSectionSchema=Base.extend({name:z.string(),purpose:z.string().default(""),order:z.number().int().default(0),beatIds:z.array(z.string()).default([])});
export const PlotOutlineSchema=Base.extend({structure:z.enum(["free","three_act","four_act","custom"]).default("three_act"),sections:z.array(PlotSectionSchema).default([]),beats:z.array(PlotBeatSchema).default([])});
export const CharacterPlanSchema=Base.extend({characterId:z.string(),characterName:z.string(),storyFunction:z.string().default(""),initialState:z.string().default(""),externalGoal:z.string().default(""),internalNeed:z.string().default(""),desire:z.string().default(""),fear:z.string().default(""),falseBelief:z.string().default(""),strengths:z.array(z.string()).default([]),weaknesses:z.array(z.string()).default([]),behaviorBoundaries:z.array(z.string()).default([]),keyChoices:z.array(z.string()).default([]),transformation:z.string().default(""),endingState:z.string().default(""),linkedCharacterCardId:z.string().default("")});
export const CharacterArcSchema=Base.extend({characterPlanId:z.string(),type:z.enum(["positive","negative","flat","tragic","open","custom"]).default("positive"),initialState:z.string().default(""),coreContradiction:z.string().default(""),incitingEventBeatId:z.string().default(""),firstActiveChoiceBeatId:z.string().default(""),escalationBeatIds:z.array(z.string()).default([]),midpointChangeBeatId:z.string().default(""),greatestFailureBeatId:z.string().default(""),finalChoiceBeatId:z.string().default(""),endingState:z.string().default(""),unresolvedQuestions:z.array(z.string()).default([])});
export const RelationshipArcSchema=Base.extend({characterIds:z.array(z.string()).min(2),initialRelationship:z.string().default(""),powerDynamic:z.string().default(""),trustState:z.string().default(""),coreConflict:z.string().default(""),sharedInterest:z.string().default(""),turningBeatIds:z.array(z.string()).default([]),finalState:z.string().default("")});
export const TimelineEventSchema=Base.extend({title:z.string(),timeType:z.enum(["date","story_day","relative","order_only"]).default("order_only"),date:z.string().default(""),storyDay:z.number().int().nullable().default(null),relativeToEventId:z.string().default(""),relativeOffset:z.number().int().nullable().default(null),order:z.number().int().default(0),duration:z.string().default(""),location:z.string().default(""),characterIds:z.array(z.string()).default([]),content:z.string().default(""),prerequisites:z.array(z.string()).default([]),result:z.string().default(""),longTermConsequences:z.array(z.string()).default([]),characterChanges:z.array(CharacterStateChangeSchema).default([]),relationshipChanges:z.array(RelationshipStateChangeSchema).default([]),worldChanges:z.array(WorldStateChangeSchema).default([]),plotBeatId:z.string().default("")});
export const StoryTimelineSchema=Base.extend({events:z.array(TimelineEventSchema).default([])});
export const PlanningIssueSchema=Base.extend({type:z.string(),severity:z.enum(["critical","major","moderate","minor","note"]),confidence:z.enum(["high","medium","low"]),beatIds:z.array(z.string()).default([]),characterIds:z.array(z.string()).default([]),rationale:z.string().default(""),minimumRevision:z.string().default(""),sideEffects:z.array(z.string()).default([])});
export const OutlineVariantSchema=Base.extend({name:z.string().default("版本 A"),description:z.string().default(""),parentVariantId:z.string().nullable().default(null),creationSource:z.enum(["user","generated","analysis_revision","alternative","imported"]).default("user"),adopted:z.boolean().default(false),storyBible:StoryBibleSchema,characterPlans:z.array(CharacterPlanSchema).default([]),characterArcs:z.array(CharacterArcSchema).default([]),relationshipArcs:z.array(RelationshipArcSchema).default([]),outline:PlotOutlineSchema,timeline:StoryTimelineSchema,issues:z.array(PlanningIssueSchema).default([]),notes:z.array(z.string()).default([]),sourceVersions:z.record(z.string(),z.string()).default({}),promptVersion:z.string().default(PLANNING_PROMPT_VERSION),provider:z.enum(["mock","openai","anthropic"]).default("mock"),model:z.string().default("")}).passthrough();
export const StoryPlanSchema=Base.extend({name:z.string().default("未命名小说规划"),variants:z.array(OutlineVariantSchema).default([]),adoptedVariantId:z.string().nullable().default(null),selectedVariantId:z.string().nullable().default(null),selectedCharacterIds:z.array(z.string()).default([]),selectedLorebookIds:z.array(z.string()).default([]),selectedAnalysisReportIds:z.array(z.string()).default([]),originalIdea:z.string().default(""),generationGoal:z.string().default(""),tokenBudget:z.number().int().min(256).default(8000)}).passthrough();
export type StoryPlan=z.infer<typeof StoryPlanSchema>;export type StoryBible=z.infer<typeof StoryBibleSchema>;export type CreativeConstraint=z.infer<typeof CreativeConstraintSchema>;export type CharacterPlan=z.infer<typeof CharacterPlanSchema>;export type CharacterArc=z.infer<typeof CharacterArcSchema>;export type RelationshipArc=z.infer<typeof RelationshipArcSchema>;export type PlotOutline=z.infer<typeof PlotOutlineSchema>;export type PlotSection=z.infer<typeof PlotSectionSchema>;export type PlotBeat=z.infer<typeof PlotBeatSchema>;export type PlotDependency=z.infer<typeof PlotDependencySchema>;export type StoryTimeline=z.infer<typeof StoryTimelineSchema>;export type TimelineEvent=z.infer<typeof TimelineEventSchema>;export type CharacterStateChange=z.infer<typeof CharacterStateChangeSchema>;export type RelationshipStateChange=z.infer<typeof RelationshipStateChangeSchema>;export type WorldStateChange=z.infer<typeof WorldStateChangeSchema>;export type OutlineVariant=z.infer<typeof OutlineVariantSchema>;export type PlanningIssue=z.infer<typeof PlanningIssueSchema>;export type PlanningSourceReference=z.infer<typeof PlanningSourceReferenceSchema>;
const now=()=>new Date().toISOString(); const base=()=>({id:createStableId("plan"),createdAt:now(),modifiedAt:now()});
export function createEmptyVariant(name="版本 A"):OutlineVariant{return OutlineVariantSchema.parse({...base(),name,storyBible:{...base()},outline:{...base()},timeline:{...base()}})}
export function createEmptyStoryPlan(name="未命名小说规划"):StoryPlan{const v=createEmptyVariant();return StoryPlanSchema.parse({...base(),name,originalIdea:"",variants:[v],adoptedVariantId:v.id,selectedVariantId:v.id})}
export function createEmptyBeat(order=0):PlotBeat{return PlotBeatSchema.parse({...base(),title:`情节节点 ${order+1}`})}
