import { z } from "zod";

const JumpSchema = z.object({ view: z.string(), sourceId: z.string(), chapterId: z.string().default(""), sceneId: z.string().default("") });
const MetaSchema = z.object({ sources: z.array(z.unknown()).default([]), version: z.string(), state: z.enum(["confirmed", "candidate", "conflict"]), conflict: z.boolean(), stale: z.boolean(), jump: JumpSchema });
const ItemSchema = MetaSchema.extend({ id: z.string(), title: z.string(), status: z.string(), chapterId: z.string().default(""), sceneId: z.string().default("") }).passthrough();
export const RelationshipGraphViewModelSchema = z.object({ nodes: z.array(ItemSchema), edges: z.array(ItemSchema.extend({ fromCharacterId: z.string(), toCharacterId: z.string(), relationship: z.string(), trust: z.string(), power: z.string(), order: z.number() })), truncated: z.boolean() });
export const TimelineViewModelSchema = z.object({ actualOrder: z.array(ItemSchema.extend({ timeType: z.string(), exactDate: z.string().nullable(), storyDay: z.number().nullable(), order: z.number(), location: z.string() })), narrativeOrder: z.array(z.any()), truncated: z.boolean() });
export const PlotThreadViewModelSchema = z.object({ items: z.array(ItemSchema.extend({ characterIds: z.array(z.string()), events: z.array(z.unknown()), stalled: z.boolean() })), truncated: z.boolean() });
export const ForeshadowViewModelSchema = z.object({ items: z.array(ItemSchema.extend({ events: z.array(z.unknown()), overdue: z.boolean() })), truncated: z.boolean() });
export const KnowledgeMatrixViewModelSchema = z.object({ columns: z.array(z.object({ id: z.string(), title: z.string() })), rows: z.array(ItemSchema.extend({ cells: z.record(z.string(), z.string()), public: z.boolean(), secret: z.boolean() })), truncated: z.boolean() });
export const PacingSeriesViewModelSchema = z.object({ points: z.array(ItemSchema.extend({ words: z.number(), scenes: z.number(), pacing: z.number(), conflictIntensity: z.number(), emotion: z.number(), action: z.number(), information: z.number(), relationshipProgress: z.number(), styleRisk: z.number().nullable() })), truncated: z.boolean() });
export const CharacterPresenceViewModelSchema = z.object({ chapters: z.array(z.object({ id: z.string(), title: z.string(), order: z.number() })), characters: z.array(ItemSchema.extend({ characterId: z.string(), chapterIds: z.array(z.string()), dialogueCount: z.number(), povChapterIds: z.array(z.string()), absenceRanges: z.array(z.string()) })), truncated: z.boolean() });
export const VisualReadModelsSchema = z.object({ signature: z.string(), generatedAt: z.string(), views: z.object({ relationshipGraph: RelationshipGraphViewModelSchema, timeline: TimelineViewModelSchema, plotThread: PlotThreadViewModelSchema, foreshadow: ForeshadowViewModelSchema, knowledgeMatrix: KnowledgeMatrixViewModelSchema, pacingSeries: PacingSeriesViewModelSchema, characterPresence: CharacterPresenceViewModelSchema }) });
export type VisualReadModels = z.infer<typeof VisualReadModelsSchema>;
