import { AssetLibraryStateSchema,AssetPackSchema,AssetUpdateProposalSchema,LibraryAssetSchema,ProjectAssetLinkSchema,TemplateInstantiationPlanSchema,type AssetLibraryState,type AssetType } from "@/domain/asset-library";
import { ChangeSetSchema } from "@/domain/change-management";
const uid=(p:string)=>`${p}_${crypto.randomUUID()}`; const now=()=>new Date().toISOString();
const json=(v:unknown)=>JSON.stringify(v); const checksum=(v:unknown)=>{let h=2166136261;for(const c of json(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16)};
export function createLibraryAsset(input:{state?:AssetLibraryState;workspaceId:string;type:AssetType;name:string;content:unknown;sourceProjectId?:string}){const state=AssetLibraryStateSchema.parse(input.state??{}),time=now(),assetId=uid("asset"),versionId=uid("assetv");const asset=LibraryAssetSchema.parse({assetId,workspaceId:input.workspaceId,type:input.type,name:input.name,currentVersionId:versionId,sourceProjectId:input.sourceProjectId??null,versions:[{versionId,assetId,versionNumber:1,content:structuredClone(input.content),createdAt:time}],createdAt:time,updatedAt:time});return{...state,assets:[...state.assets,asset]}}
export function addAssetVersion(state:AssetLibraryState,assetId:string,content:unknown,summary:string){const time=now();return{...state,assets:state.assets.map(asset=>{if(asset.assetId!==assetId)return asset;const version={versionId:uid("assetv"),assetId,versionNumber:asset.versions.length+1,content:structuredClone(content),contentSchemaVersion:1,parentVersionId:asset.currentVersionId,changeSummary:summary,sourceReferences:[],dependencyIds:[],createdAt:time,createdBy:"user",status:"active" as const};return{...asset,currentVersionId:version.versionId,versions:[...asset.versions,version],updatedAt:time}})}}
export function addAssetToProject(state:AssetLibraryState,assetId:string,projectId:string,mode:"copy"|"reference"|"derived"|"template_instance",targetType:string,targetId:string,localOverrides:Record<string,unknown>={}){const asset=state.assets.find(x=>x.assetId===assetId);if(!asset)throw new Error("素材不存在");const time=now(),link=ProjectAssetLinkSchema.parse({linkId:uid("alink"),projectId,assetId,sourceVersionId:asset.currentVersionId,mode,targetType,targetId,localOverrides,status:Object.keys(localOverrides).length?"locally_modified":"current",lastCheckedAt:time,lastAppliedVersionId:asset.currentVersionId,createdAt:time,updatedAt:time});return{...state,links:[...state.links,link]}}
export const disconnectAssetLink=(s:AssetLibraryState,id:string)=>({...s,links:s.links.map(x=>x.linkId===id?{...x,status:"disconnected" as const,updatedAt:now()}:x)});export const pinAssetLink=(s:AssetLibraryState,id:string)=>({...s,links:s.links.map(x=>x.linkId===id?{...x,pinned:true,updatedAt:now()}:x)});
export function buildAssetUpdateProposal(state:AssetLibraryState,linkId:string){const link=state.links.find(x=>x.linkId===linkId);if(!link)throw new Error("素材引用不存在");const asset=state.assets.find(x=>x.assetId===link.assetId);const base=asset?.versions.find(x=>x.versionId===link.sourceVersionId)?.content??null,upstream=asset?.versions.find(x=>x.versionId===asset.currentVersionId)?.content??null;const changed=Boolean(asset&&asset.currentVersionId!==link.sourceVersionId),local=Object.keys(link.localOverrides).length>0,status=!asset?"source_missing":changed&&local?"conflict":changed?"update_available":"current";const time=now(),changeSet=ChangeSetSchema.parse({changeSetId:uid("change"),projectId:link.projectId,sourceProposalId:`asset:${linkId}`,changeType:"custom",targetType:link.targetType,targetIds:[link.targetId],previousValue:base,proposedValue:upstream,reason:`素材更新：${asset?.name??link.assetId}`,status:"draft",createdAt:time,updatedAt:time});return AssetUpdateProposalSchema.parse({proposalId:uid("assetproposal"),linkId,status,baseContent:base,upstreamContent:upstream,localOverrides:link.localOverrides,changeSet,applied:false})}
export function checkAssetDependencies(state:AssetLibraryState){const ids=new Set(state.assets.map(x=>x.assetId)),missing=[...new Set(state.dependencies.filter(x=>!x.optional&&!ids.has(x.dependencyAssetId)).map(x=>x.dependencyAssetId))],graph=new Map<string,string[]>();for(const d of state.dependencies){graph.set(d.assetId,[...(graph.get(d.assetId)??[]),d.dependencyAssetId])}const cycles:string[][]=[];const visit=(n:string,path:string[])=>{const at=path.indexOf(n);if(at>=0){cycles.push([...path.slice(at),n]);return}for(const v of graph.get(n)??[])visit(v,[...path,n])};for(const id of ids)visit(id,[]);return{missing,cycles}}
function sanitizeTemplate(v:unknown):unknown{if(Array.isArray(v))return v.map(sanitizeTemplate);if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v as Record<string,unknown>).filter(([k])=>!/(manuscript|draft|chat|dialog|token|key|secret|log)/i.test(k)).map(([k,x])=>[k,sanitizeTemplate(x)]));return v}
export function createTemplateInstantiationPlan(state:AssetLibraryState,assetId:string,projectName:string,_options:{includeManuscript:boolean}){const asset=state.assets.find(x=>x.assetId===assetId&&x.type==="project_template");if(!asset)throw new Error("项目模板不存在");const version=asset.versions.find(x=>x.versionId===asset.currentVersionId)!;return TemplateInstantiationPlanSchema.parse({planId:uid("tpl"),templateAssetId:assetId,templateVersionId:version.versionId,projectName,preview:sanitizeTemplate(version.content),createdAt:now()})}
export function exportAssetPack(state:AssetLibraryState,ids:string[]){const assets=state.assets.filter(x=>ids.includes(x.assetId)),dependencies=state.dependencies.filter(x=>ids.includes(x.assetId));const core={schemaVersion:1 as const,manifest:{name:"Story Card Studio 素材包",createdAt:now(),assetCount:assets.length},assets,dependencies};return JSON.stringify({...core,checksum:checksum(core)},null,2)}
export function importAssetPack(raw:string){const parsed=AssetPackSchema.parse(JSON.parse(raw)),core={schemaVersion:parsed.schemaVersion,manifest:parsed.manifest,assets:parsed.assets,dependencies:parsed.dependencies};if(checksum(core)!==parsed.checksum)throw new Error("素材包校验失败");return AssetLibraryStateSchema.parse({assets:parsed.assets,dependencies:parsed.dependencies})}
export function searchAssets(state:AssetLibraryState,query="",type?:AssetType){const q=query.trim().toLocaleLowerCase();return state.assets.filter(x=>!x.archived&&(!type||x.type===type)&&(!q||`${x.name} ${x.description} ${x.tags.join(" ")} ${JSON.stringify(x.versions.find(v=>v.versionId===x.currentVersionId)?.content)}`.toLocaleLowerCase().includes(q))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
