import { z } from "zod"; import type { ProjectDraft } from "@/domain/project-draft"; import { ContinuitySourceReferenceSchema,createContinuitySource } from "@/domain/continuity"; import { buildProjectEntityIndex,searchProjectIndex } from "./continuity-index"; import { queryVisualReadModels } from "./visual-read-model"; import { searchAssets } from "./asset-library";
type Permission="read"|"propose_change"|"execute_confirmed_change"; type Operation="read"|"analyze"|"generate"|"propose_change"|"execute_confirmed_change";
export interface AssistantToolDefinition{toolId:string;name:string;description:string;inputSchema:z.ZodTypeAny;outputSchema:z.ZodTypeAny;permission:Permission;operationType:Operation;supportedScopes:string[];timeoutMs:number;sourceRequirement:boolean;handler(input:any,signal:AbortSignal):Promise<any>}
export class AssistantToolRegistry{private tools=new Map<string,AssistantToolDefinition>();register(tool:AssistantToolDefinition){if(this.tools.has(tool.toolId))throw new Error(`工具重复：${tool.toolId}`);this.tools.set(tool.toolId,tool)}list(){return[...this.tools.values()].map(({handler:_,...tool})=>tool)}async execute(id:string,input:unknown,auth:{allowConfirmedWrite:boolean},signal?:AbortSignal):Promise<any>{const tool=this.tools.get(id);if(!tool)throw new Error(`工具不存在：${id}`);if(tool.permission==="execute_confirmed_change"&&!auth.allowConfirmedWrite)throw new Error("写入工具需要用户确认。");const parsed=tool.inputSchema.parse(input);const controller=new AbortController();const onAbort=()=>controller.abort();signal?.addEventListener("abort",onAbort,{once:true});const timer=setTimeout(()=>controller.abort(),tool.timeoutMs);try{const result=await tool.handler(parsed,controller.signal);return tool.outputSchema.parse(result)}finally{clearTimeout(timer);signal?.removeEventListener("abort",onAbort)}}}
const Output=z.object({summary:z.string(),data:z.unknown(),sources:z.array(ContinuitySourceReferenceSchema)}); const Input=z.object({query:z.string().default("")});
export function createDefaultAssistantRegistry(draft:ProjectDraft){const registry=new AssistantToolRegistry();const continuity=draft.continuityProjects.find(x=>x.id===draft.selectedContinuityProjectId)??draft.continuityProjects[0];const add=(toolId:string,name:string,handler:(q:string)=>{summary:string;data:unknown;sources:any[]})=>registry.register({toolId,name,description:name,inputSchema:Input,outputSchema:Output,permission:"read",operationType:"read",supportedScopes:["project","chapter","scene","character"],timeoutMs:5000,sourceRequirement:true,handler:async({query})=>handler(query)});
  add("project.search","项目搜索",q=>{const entities=searchProjectIndex(buildProjectEntityIndex(draft,continuity?.entities,continuity),q).slice(0,20);return{summary:entities.map(x=>`${x.name}：${x.description.slice(0,120)}`).join("\n")||"没有找到匹配资料。",data:entities,sources:entities.flatMap(x=>x.sources)}});
  add("canon.query","Canon 查询",q=>{const facts=(continuity?.canonLedger.facts??[]).filter(x=>!q||`${x.title}${x.content}`.includes(q)).slice(0,20);return{summary:facts.map(x=>`${x.title}：${x.content}`).join("\n")||"没有匹配 Canon。",data:facts,sources:facts.flatMap(x=>x.sources.length?x.sources:[createContinuitySource("canon",x.id,{sourceName:x.title,excerpt:x.content.slice(0,180),version:x.modifiedAt,classification:"confirmed_fact"})])}});
  add("continuity.query","连续性查询",q=>{const items=[...(continuity?.issues??[]),...(continuity?.relationshipSnapshots??[]),...(continuity?.characterSnapshots??[]),...(continuity?.knowledgeStates??[])].filter(x=>!q||JSON.stringify(x).includes(q)).slice(0,30);return{summary:`找到 ${items.length} 条状态或连续性资料。`,data:items,sources:items.flatMap(x=>x.sources)}});
  add("timeline.query","时间线查询",q=>{const items=(continuity?.timeline.events??[]).filter(x=>!q||JSON.stringify(x).includes(q));return{summary:items.map(x=>x.title).join("、")||"没有时间线事件。",data:items,sources:items.flatMap(x=>x.sources)}});
  add("threads.query","剧情线与伏笔",q=>{const items=[...(continuity?.plotThreads??[]),...(continuity?.foreshadowThreads??[])].filter(x=>!q||JSON.stringify(x).includes(q));return{summary:items.map(x=>`${x.title}（${x.status}）`).join("、")||"没有匹配剧情线或伏笔。",data:items,sources:items.flatMap(x=>x.sources)}});
  add("visual.query","可视化查询",()=>{const data=queryVisualReadModels(draft,{maxNodes:200});return{summary:"已生成关系、时间线、剧情线、伏笔、知情、节奏和角色出场只读数据。",data,sources:(continuity?.timeline.events??[]).flatMap(x=>x.sources).slice(0,20)}});
  add("library.search","素材搜索",q=>{const items=searchAssets(draft.assetLibrary,q).slice(0,30);return{summary:items.map(x=>`${x.name}（${x.type}）`).join("、")||"没有匹配素材。",data:items,sources:items.flatMap(x=>x.sourceReferences)}});
  add("project.overview","项目概况",()=>({summary:`角色：${draft.characterCard.data.name||"未命名"}；世界书 ${draft.lorebooks.length} 本；正文 ${draft.manuscripts.length} 份。`,data:{lorebooks:draft.lorebooks.length,manuscripts:draft.manuscripts.length,progress:continuity?.writingProgress},sources:[createContinuitySource("character_card",draft.characterCard.data.name||"current",{sourceName:"当前角色卡",excerpt:draft.characterCard.data.description.slice(0,180),version:draft.savedAt,classification:"source_setting"})]}));return registry}
