import { ForeshadowItemSchema, InformationItemSchema, InformationRevealSchema, createEmptyChapter, createEmptyChapterPlanningProject, createEmptyScene, createEmptyVolume, type ChapterPlanningProject } from "@/domain/chapter-planning";
import { createStableId } from "@/domain/lorebook";

const base=(prefix:string)=>({id:createStableId(prefix),createdAt:new Date().toISOString(),modifiedAt:new Date().toISOString()});
export function createMockChapterPlanningProject():ChapterPlanningProject{
  const project=createEmptyChapterPlanningProject("mock-b1-plan","mock-b1-variant");project.name="古玉迷局·章节规划";const volumes=[createEmptyVolume(0),createEmptyVolume(1)];volumes[0].title="第一卷：烟雨疑云";volumes[0].goal="发现古玉与失踪案的联系";volumes[0].coreConflict="守护秘密与追查真相";volumes[0].openingState="主角独自守秘";volumes[0].endingState="主角被迫寻找盟友";volumes[0].expectedChapterCount=4;volumes[1].title="第二卷：共同承担";volumes[1].goal="阻止秘密被滥用并完成角色选择";volumes[1].coreConflict="公开真相的代价";volumes[1].openingState="同盟脆弱";volumes[1].endingState="共同承担后果";volumes[1].expectedChapterCount=3;
  for(let i=0;i<7;i++){const volume=volumes[i<4?0:1];const chapter=createEmptyChapter(volume.id,i<4?i:i-4);const version=chapter.versions[0];version.title=`第 ${i+1} 章：${["雨夜来客","古玉异响","错误的线索","被迫结盟","潜入旧宅","真相与背叛","共同选择"][i]}`;version.chapterGoal=["建立谜题","确认异常","制造误导","改变关系","取得证据","支付代价","解决核心冲突"][i];version.mainConflict="追查真相受到阻碍";version.trigger="新线索迫使角色行动";version.coreTurn="原有判断被新事实改变";version.result="角色获得新信息并承担后果";version.hook.content="新的危险逼近";version.characterIds=["柳如烟","旅人"];version.stateChanges=["信任和风险发生变化"];version.informationChanges=[`信息${i+1}被揭示`];version.pacingIntensity=i===5?5:3;version.conflictIntensity=i===5?5:3;version.adopted=true;
    if(i===0){for(let s=0;s<3;s++){const scene=createEmptyScene(chapter.id,s);const sv=scene.versions[0];sv.title=["雨中相遇","古玉示警","陌生脚印"][s];sv.sceneGoal=["引入旅人","触发异常","留下追查目标"][s];sv.presentCharacterIds=s===2?["柳如烟"]:["柳如烟","旅人"];sv.characterGoals={"柳如烟":"保护古玉","旅人":"确认传闻"};sv.opposingForce="信息不对等";sv.conflictType="秘密与信任";sv.trigger="外界事件打破平静";sv.action="角色试探并作出选择";sv.turningPoint="出现超出预期的证据";sv.result="局面不可恢复到原状";sv.sceneFunctions=s===0?["setup","relationship"]:s===1?["conflict","reveal"]:["reversal","transition"];sv.entryState.time=`故事第1天 ${s+1}`;sv.exitState.time=`故事第1天 ${s+2}`;sv.entryState.location=s===2?"院外":"柳宅";sv.exitState.location=s===1?"院外":"柳宅";sv.entryState.presentCharacterIds=sv.presentCharacterIds;sv.exitState.presentCharacterIds=sv.presentCharacterIds;sv.entryState.emotionStates={"柳如烟":s===0?"平静":"警惕"};sv.exitState.emotionStates={"柳如烟":"警惕"};sv.pov.povCharacterIds=s===1?["柳如烟","旅人"]:["柳如烟"];sv.pov.allowSwitch=false;sv.nextSceneConnection="结果触发下一场";sv.adopted=true;version.scenes.push(scene)}}
    volume.chapters.push(chapter)}
  const firstChapter=volumes[0].chapters[0];const firstVersion=firstChapter.versions[0];firstVersion.lockedFields=["chapterGoal"];
  const alternative=structuredClone(firstVersion);alternative.id=createStableId("chapter_version");alternative.name="章节方案 B";alternative.parentVersionId=firstVersion.id;alternative.creationReason="mock_alternative";alternative.adopted=false;alternative.coreTurn="旅人先公开自己的线索，换取柳如烟有限合作";alternative.modifiedAt=new Date().toISOString();firstChapter.versions.push(alternative);
  firstVersion.scenes[2].versions[0].entryState.location="河岸";
  project.volumes=volumes;project.selectedVolumeId=volumes[0].id;project.selectedChapterId=volumes[0].chapters[0].id;project.selectedSceneId=volumes[0].chapters[0].versions[0].scenes[0].id;
  const information=InformationItemSchema.parse({...base("info"),title:"古玉会对危险产生反应",content:"古玉异响与危险接近有关",readerState:"unknown",characterStates:{"柳如烟":"unknown"},secrecy:"secret",verification:"unverified",expectedResolution:"第二卷验证"});project.informationItems=[information];firstVersion.scenes[1].versions[0].entryState.knownInformationIds=[information.id];
  const sceneId=volumes[0].chapters[0].versions[0].scenes[1].id;const reveal=InformationRevealSchema.parse({...base("reveal"),informationItemId:information.id,chapterId:volumes[0].chapters[0].id,sceneId,target:"reader",method:"古玉发热",sourceReferenceIds:["mock-source"],isFirstReveal:true,order:1});project.informationReveals=[reveal];volumes[0].chapters[0].versions[0].scenes[1].versions[0].informationRevealIds=[reveal.id];
  const foreshadow=ForeshadowItemSchema.parse({...base("foreshadow"),label:"水纹刻痕",setupLocationIds:[volumes[0].chapters[0].versions[0].scenes[0].id],reinforcementLocationIds:[volumes[0].chapters[2].id],plannedPayoffLocationIds:[volumes[1].chapters[1].id],actualPayoffLocationIds:[volumes[1].chapters[1].id],state:"paid_off",notes:"基础铺垫与回收案例"});project.foreshadows=[foreshadow];return project;
}
