import { describe, expect, it } from "vitest";
import { createEmptyProjectDraft } from "@/domain/project-draft"; import { createMockContinuityProject } from "@/services/continuity-mock"; import { createChangeProposal } from "@/services/change-proposal"; import { changeSetFromProposal } from "@/services/change-set"; import { buildDependencyIndex } from "@/services/dependency-index"; import { analyzeChangeImpact } from "@/services/change-impact-analyzer"; import { createPropagationPlan, executePropagationPlan, retryPropagationPlan, revertPropagationResult } from "@/services/change-propagation";
function fixture() { const draft = createEmptyProjectDraft(); const continuity = createMockContinuityProject(); draft.continuityProjects = [continuity]; draft.selectedContinuityProjectId = continuity.id; return draft; }
const changeFor = (draft: ReturnType<typeof fixture>) => changeSetFromProposal(createChangeProposal({ conversationId: "c", userRequest: "改名", operation: "rename", targetType: "entity", targetIds: ["char-liu"], currentValue: "柳如烟", proposedValue: "柳烟", sourceVersion: draft.savedAt }), "project");
describe("设定变更与影响管理", () => {
  it("converts a proposal to a draft change set and indexes dependencies incrementally", () => { const draft = fixture(); const change = changeFor(draft); expect(change.status).toBe("draft"); const first = buildDependencyIndex(draft); expect(first.edges.length).toBeGreaterThan(0); expect(buildDependencyIndex(draft, first)).toBe(first); });
  it("separates direct, downstream and possible name impacts without merging same-name entities", () => { const draft = fixture(); const impacts = analyzeChangeImpact(changeFor(draft), draft, buildDependencyIndex(draft)); expect(impacts.some((x) => x.impactType === "direct")).toBe(true); expect(impacts.some((x) => ["downstream", "possible", "stale"].includes(x.impactType))).toBe(true); expect(impacts.filter((x) => x.impactType === "possible").every((x) => x.canAutoPrepare === false)).toBe(true); });
  it("plans no default operations, orders selected operations, and executes idempotently with retcon/stale support", () => { const draft = fixture(); const change = changeFor(draft); const impacts = analyzeChangeImpact(change, draft, buildDependencyIndex(draft)); expect(createPropagationPlan(change, impacts, []).operations).toHaveLength(0); const selected = impacts.filter((x) => x.targetType === "canon" || x.impactType === "stale").slice(0, 3).map((x) => x.impactId); const plan = createPropagationPlan(change, impacts, selected); expect(plan.operations.map((x) => x.order)).toEqual([...plan.operations.map((x) => x.order)].sort((a, b) => a - b)); const first = executePropagationPlan(draft, change, plan); const second = executePropagationPlan(first.draft, change, plan, first.result); expect(second.result.operations.filter((x) => x.executionStatus === "applied")).toHaveLength(first.result.operations.filter((x) => x.executionStatus === "applied").length); expect(retryPropagationPlan(first.draft, change, plan, first.result).result.planId).toBe(plan.planId); expect(revertPropagationResult(first.draft, first.result).status).toBe("reverted"); });
});
