"use client";

import { useMemo, useRef, useState } from "react";
import type { ProjectDraft } from "@/domain/project-draft";
import {
  CanonConflictSchema, OpenQuestionSchema, PlotThreadSchema, ForeshadowThreadSchema,
  createEmptyContinuityProject, createCanonFact, createContinuitySource, continuityBase, continuityNow,
  type ContinuityProject, type CanonFact, type ContinuityIssue,
} from "@/domain/continuity";
import { extractCanonCandidates, confirmCanonFact, mergeCanonFacts, resolveCanonConflict, createRetcon } from "@/services/continuity-canon";
import { buildProjectEntityIndex, searchProjectIndex } from "@/services/continuity-index";
import {
  deriveSnapshots, integrateProjectTimeline, summarizeAcceptedManuscript, markStaleSummaries, analyzePlanManuscriptDrift,
  validateContinuity, calculateWritingProgress, buildProjectHealthReport, buildNextChapterContextPackage,
  importB2Foreshadows, createPlotThreadsFromPlans,
} from "@/services/continuity-engine";
import { buildContinuityContext } from "@/services/continuity-context-builder";
import { createMockContinuityProject } from "@/services/continuity-mock";
import { downloadContinuity, exportContinuityJSON, exportContinuityMarkdown, importContinuityJSON } from "@/services/continuity-export";
import { readValidatedJsonFile } from "@/services/file-validation";

type View = "overview" | "canon" | "entities" | "states" | "knowledge" | "threads" | "questions" | "foreshadow" | "timeline" | "summaries" | "drift" | "issues" | "search" | "progress" | "next";
const VIEWS: Array<[View, string]> = [["overview", "概览"], ["canon", "Canon"], ["entities", "实体"], ["states", "状态"], ["knowledge", "知情矩阵"], ["threads", "剧情线"], ["questions", "未解决问题"], ["foreshadow", "伏笔"], ["timeline", "时间线"], ["summaries", "摘要"], ["drift", "偏差"], ["issues", "连续性问题"], ["search", "检索"], ["progress", "写作进度"], ["next", "下一章上下文"]];
const severityOrder = ["critical", "major", "moderate", "minor", "note"];
const box: React.CSSProperties = { border: "1px solid var(--color-border)", borderRadius: "var(--radius-card)", padding: 14, background: "var(--color-surface-raised)", boxShadow: "var(--shadow-subtle)" };
const row: React.CSSProperties = { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" };
const button: React.CSSProperties = { padding: "7px 12px", border: "1px solid var(--color-border-control)", borderRadius: "var(--radius-control)", background: "var(--color-surface-raised)", color: "var(--color-text)", cursor: "pointer" };
const primary: React.CSSProperties = { ...button, background: "var(--color-primary)", color: "white", borderColor: "var(--color-primary)" };
const input: React.CSSProperties = { padding: "8px 10px", border: "1px solid var(--color-border-control)", borderRadius: "var(--radius-control)", minWidth: 180 };

function Stat({ label, value, tone }: { label: string; value: string | number; tone?: string }) { return <div style={{ ...box, minWidth: 128 }}><div style={{ fontSize: 12, color: "var(--color-text-secondary)" }}>{label}</div><div style={{ fontSize: 24, fontWeight: 700, color: tone }}>{value}</div></div>; }
function Sources({ sources }: { sources: CanonFact["sources"] }) { return <details><summary>来源 {sources.length}</summary>{sources.length ? <ul>{sources.map((s, i) => <li key={`${s.sourceType}-${s.sourceId}-${i}`}>{s.valid ? "✓" : "⚠"} {s.sourceType} · {s.sourceName || s.sourceId} · 权威 {s.authority}{s.excerpt ? `：${s.excerpt}` : ""}</li>)}</ul> : <p>无来源（需人工补充）</p>}</details>; }

export function ContinuityCenter({ draft, projects, selected, onAdd, onUpdate, onDelete, onSelect }: {
  draft: ProjectDraft; projects: ContinuityProject[]; selected: ContinuityProject | null;
  onAdd(project: ContinuityProject): void; onUpdate(project: ContinuityProject): void; onDelete(id: string): void; onSelect(id: string | null): void;
}) {
  const [view, setView] = useState<View>("overview"); const [query, setQuery] = useState(""); const [typeFilter, setTypeFilter] = useState("");
  const [canonStatus, setCanonStatus] = useState(""); const [issueSeverity, setIssueSeverity] = useState(""); const [issueType, setIssueType] = useState("");
  const [newTitle, setNewTitle] = useState(""); const [newContent, setNewContent] = useState(""); const [selectedFactIds, setSelectedFactIds] = useState<string[]>([]);
  const importRef = useRef<HTMLInputElement>(null);
  const update = (fn: (project: ContinuityProject) => ContinuityProject) => { if (selected) onUpdate({ ...fn(structuredClone(selected)), modifiedAt: continuityNow() }); };

  const bootstrap = (name = "连续性项目") => {
    let project = createEmptyContinuityProject(name);
    project.canonLedger.facts = extractCanonCandidates({ card: draft.characterCard, lorebooks: draft.lorebooks, manuscripts: draft.manuscripts });
    const snapshots = deriveSnapshots(draft.chapterPlanningProjects, draft.manuscripts); project.characterSnapshots = snapshots.characters; project.relationshipSnapshots = snapshots.relationships; project.worldSnapshots = snapshots.worlds; project.knowledgeStates = snapshots.knowledge;
    project.plotThreads = createPlotThreadsFromPlans(draft.storyPlans); project.foreshadowThreads = importB2Foreshadows(draft.chapterPlanningProjects);
    for (const manuscript of draft.manuscripts) { const summaries = summarizeAcceptedManuscript(manuscript); project.sceneSummaries.push(...summaries.scenes); project.chapterSummaries.push(...summaries.chapters); }
    project.drifts = analyzePlanManuscriptDrift(draft.chapterPlanningProjects, draft.manuscripts); project.timeline = integrateProjectTimeline(draft.storyPlans, draft.chapterPlanningProjects, project); project.entities = buildProjectEntityIndex(draft, [], project);
    project.writingProgress = calculateWritingProgress(draft.manuscripts, draft.chapterPlanningProjects); project.issues = validateContinuity(project);
    project.healthReports = [buildProjectHealthReport(project)]; project.contextPackages = [buildNextChapterContextPackage(project, draft.chapterPlanningProjects[0] ?? null)];
    project.sourceVersions = { characterCard: draft.characterCard.data.character_version, projectDraft: String(draft.dataVersion), savedAt: draft.savedAt };
    onAdd(project);
  };

  const refreshAll = () => update((project) => {
    project.entities = buildProjectEntityIndex(draft, project.entities, project);
    const snapshots = deriveSnapshots(draft.chapterPlanningProjects, draft.manuscripts); if (!project.characterSnapshots.length) project.characterSnapshots = snapshots.characters; if (!project.relationshipSnapshots.length) project.relationshipSnapshots = snapshots.relationships; if (!project.worldSnapshots.length) project.worldSnapshots = snapshots.worlds; if (!project.knowledgeStates.length) project.knowledgeStates = snapshots.knowledge;
    const stale = markStaleSummaries(draft.manuscripts, project.sceneSummaries, project.chapterSummaries); project.sceneSummaries = stale.scenes; project.chapterSummaries = stale.chapters;
    project.drifts = analyzePlanManuscriptDrift(draft.chapterPlanningProjects, draft.manuscripts); project.timeline = integrateProjectTimeline(draft.storyPlans, draft.chapterPlanningProjects, project);
    project.writingProgress = calculateWritingProgress(draft.manuscripts, draft.chapterPlanningProjects, project.writingProgress.goals); project.issues = validateContinuity(project);
    project.healthReports.push(buildProjectHealthReport(project)); return project;
  });

  const entityResults = useMemo(() => selected ? searchProjectIndex(selected.entities, query, { types: typeFilter ? [typeFilter as never] : undefined }) : [], [selected, query, typeFilter]);
  const context = useMemo(() => selected ? buildContinuityContext(draft, selected, query, 18000) : null, [draft, selected, query]);

  if (!selected) return <section style={{ display: "grid", gap: 16 }}><div style={box}><h2 style={{ marginTop: 0 }}>连续性中心</h2><p>建立连续性项目后，Canon、跨章状态、剧情线、伏笔、偏差和正式写作进度会与角色卡、世界书、规划和正文通过稳定 ID 关联。</p><div style={row}><button style={primary} onClick={() => bootstrap()}>从当前项目建立</button><button style={button} onClick={() => onAdd(createMockContinuityProject())}>加载连续性示例</button><button style={button} onClick={() => importRef.current?.click()}>导入 JSON</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={async (e) => { const file = e.target.files?.[0]; if (file) onAdd(importContinuityJSON(await readValidatedJsonFile(file))); e.currentTarget.value = ""; }} /></div></div>{projects.length > 0 && <div style={box}><h3>已有项目</h3>{projects.map((p) => <button key={p.id} style={button} onClick={() => onSelect(p.id)}>{p.name}</button>)}</div>}</section>;

  const health = selected.healthReports.at(-1); const visibleFacts = selected.canonLedger.facts.filter((f) => (!canonStatus || f.status === canonStatus) && (!query || `${f.title} ${f.content}`.toLowerCase().includes(query.toLowerCase())));
  const visibleIssues = selected.issues.filter((i) => (!issueSeverity || i.severity === issueSeverity) && (!issueType || i.type === issueType)).sort((a, b) => severityOrder.indexOf(a.severity) - severityOrder.indexOf(b.severity));

  return <section className="continuity-center" style={{ display: "grid", gap: 14 }}>
    <div style={{ ...box, ...row, justifyContent: "space-between" }}><div><h2 style={{ margin: 0 }}>{selected.name}</h2><small>数据版本 {selected.dataVersion} · {selected.provider}/{selected.model}</small></div><div style={row}><select style={input} value={selected.id} onChange={(e) => onSelect(e.target.value)}>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button style={button} onClick={refreshAll}>刷新全书索引</button><button style={button} onClick={() => downloadContinuity(exportContinuityMarkdown(selected), selected.name, "markdown")}>导出 Markdown</button><button style={button} onClick={() => downloadContinuity(exportContinuityJSON(selected), selected.name, "json")}>导出 JSON</button><button style={button} onClick={() => importRef.current?.click()}>导入</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={async (e) => { const f = e.target.files?.[0]; if (f) onAdd(importContinuityJSON(await readValidatedJsonFile(f))); e.currentTarget.value = ""; }} /><button style={{ ...button, color: "var(--color-error)" }} onClick={() => { if (confirm("删除连续性项目？不会删除角色卡、世界书、规划或正文。")) onDelete(selected.id); }}>删除</button></div></div>
    <nav style={{ ...row, overflowX: "auto", paddingBottom: 4 }}>{VIEWS.map(([id, label]) => <button key={id} style={view === id ? primary : button} onClick={() => setView(id)}>{label}</button>)}</nav>

    {view === "overview" && <><div style={row}><Stat label="正式字数" value={health?.totalWords ?? selected.writingProgress.totalWords} /><Stat label="Canon 冲突" value={selected.canonLedger.conflicts.filter((c) => c.status === "open").length} tone="var(--color-error)" /><Stat label="严重问题" value={health?.severeIssues ?? 0} tone="var(--color-error)" /><Stat label="活跃剧情线" value={selected.plotThreads.filter((t) => t.status === "active").length} /><Stat label="待回收伏笔" value={health?.pendingForeshadows ?? 0} /><Stat label="待确认事实" value={selected.canonLedger.facts.filter((f) => f.status === "candidate").length} /></div><div style={box}><h3>项目健康与优先级</h3>{health ? <><p>章节完成 {health.chapterCompletion}% · 场景完成 {health.sceneCompletion}% · 过期摘要 {health.staleSummaries} · 开放偏差 {health.drifts}</p><ol>{health.priorities.map((p) => <li key={p}>{p}</li>)}</ol></> : <p>点击“刷新全书索引”生成健康报告。</p>}</div><div style={box}><h3>本次模型上下文预览</h3><p>{context?.totalCharacters}/{context?.budget} 字符{context?.truncated ? " · 已按权威与相关性截断" : ""}；不会无差别发送整个项目。</p><details><summary>查看 {context?.items.filter((i) => i.included).length ?? 0} 项实际资料</summary><ul>{context?.items.filter((i) => i.included).map((i) => <li key={`${i.sourceType}-${i.sourceId}`}>权威 {i.authority} · {i.title}{i.locked ? "（锁定）" : ""}{i.truncated ? "（截断）" : ""}</li>)}</ul></details></div></>}

    {view === "canon" && <div style={{ display: "grid", gap: 12 }}><div style={{ ...box, ...row }}><input style={input} placeholder="事实标题" value={newTitle} onChange={(e) => setNewTitle(e.target.value)} /><input style={{ ...input, flex: 1 }} placeholder="事实内容" value={newContent} onChange={(e) => setNewContent(e.target.value)} /><button style={primary} onClick={() => { if (!newContent.trim()) return; update((p) => { p.canonLedger.facts.push(createCanonFact({ title: newTitle || newContent.slice(0, 24), content: newContent, status: "candidate", authority: 9, sources: [createContinuitySource("user", `manual-${Date.now()}`, { sourceName: "用户手动输入", authority: 9, classification: "user_assumption" })] })); return p; }); setNewTitle(""); setNewContent(""); }}>新增候选</button><button style={button} onClick={() => update((p) => { p.canonLedger.facts.push(...extractCanonCandidates({ card: draft.characterCard, lorebooks: draft.lorebooks, manuscripts: draft.manuscripts })); return p; })}>重新提取候选</button><select style={input} value={canonStatus} onChange={(e) => setCanonStatus(e.target.value)}><option value="">全部状态</option>{["locked", "confirmed", "derived", "candidate", "disputed", "retconned", "deprecated"].map((s) => <option key={s}>{s}</option>)}</select><input style={input} placeholder="搜索 Canon" value={query} onChange={(e) => setQuery(e.target.value)} /><button style={button} disabled={selectedFactIds.length < 2} onClick={() => update((p) => ({ ...p, canonLedger: mergeCanonFacts(p.canonLedger, selectedFactIds, { title: "合并事实" }) }))}>显式合并</button></div>
      {visibleFacts.map((fact) => <article key={fact.id} style={box}><div style={{ ...row, justifyContent: "space-between" }}><label><input type="checkbox" checked={selectedFactIds.includes(fact.id)} onChange={() => setSelectedFactIds((ids) => ids.includes(fact.id) ? ids.filter((id) => id !== fact.id) : [...ids, fact.id])} /> <strong>{fact.title}</strong></label><span>{fact.status} · 权威 {fact.authority}{fact.locked ? " · 🔒" : ""}</span></div><textarea style={{ ...input, width: "100%", marginTop: 8, boxSizing: "border-box" }} rows={3} value={fact.content} onChange={(e) => update((p) => { const f = p.canonLedger.facts.find((x) => x.id === fact.id); if (f && !f.locked) { f.content = e.target.value; f.modifiedAt = continuityNow(); } return p; })} disabled={fact.locked} /><div style={{ ...row, marginTop: 8 }}><button style={button} onClick={() => update((p) => ({ ...p, canonLedger: confirmCanonFact(p.canonLedger, fact.id) }))}>确认</button><button style={button} onClick={() => update((p) => ({ ...p, canonLedger: confirmCanonFact(p.canonLedger, fact.id, true) }))}>确认并锁定</button><button style={button} onClick={() => { const content = prompt("Retcon 后的新事实", fact.content); const reason = content ? prompt("Retcon 原因（必填）", "") : null; if (content && reason) update((p) => ({ ...p, canonLedger: createRetcon(p.canonLedger, fact.id, { content, title: fact.title }, { reason }) })); }}>创建 Retcon</button><button style={button} onClick={() => update((p) => { const f = p.canonLedger.facts.find((x) => x.id === fact.id); if (f && !f.locked) f.status = "deprecated"; return p; })}>废弃</button></div><Sources sources={fact.sources} /></article>)}
      <div style={box}><h3>冲突处理</h3>{selected.canonLedger.conflicts.length === 0 ? <p>暂无记录的冲突。</p> : selected.canonLedger.conflicts.map((c) => <div key={c.id} style={{ borderTop: "1px solid var(--color-border)", padding: "10px 0" }}><strong>{c.conflictType}</strong> · {c.status}<p>{c.description}</p><div style={row}>{(["keep_old", "adopt_new", "set_effective_time", "keep_both", "false_positive", "deferred"] as const).map((resolution) => <button key={resolution} style={button} onClick={() => update((p) => ({ ...p, canonLedger: resolveCanonConflict(p.canonLedger, c.id, resolution, "用户在冲突解决器中选择") }))}>{resolution}</button>)}</div></div>)}</div>
      <div style={box}><h3>Retcon 历史</h3>{selected.canonLedger.retcons.map((r) => <p key={r.id}><strong>{r.reason}</strong> · {r.oldFactId} → {r.newFactId} · 影响章节 {r.affectedChapterIds.join("、") || "未指定"}</p>)}</div></div>}

    {view === "entities" && <div style={{ display: "grid", gap: 12 }}><div style={{ ...box, ...row }}><input style={input} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="名称、别名、正文关键词" /><select style={input} value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}><option value="">全部类型</option>{["character", "location", "organization", "item", "ability", "world_rule", "event", "secret", "chapter", "scene"].map((t) => <option key={t}>{t}</option>)}</select><button style={button} onClick={() => update((p) => { p.entities = buildProjectEntityIndex(draft, p.entities, p); return p; })}>重建本地索引</button></div>{entityResults.map((e) => <article style={box} key={e.id}><strong>{e.name}</strong> · {e.entityType} · {e.status}<p>{e.description.slice(0, 300)}</p><small>别名：{e.aliases.map((a) => a.value).join("、") || "无"} · 章节 {e.chapterIds.length} · 场景 {e.sceneIds.length}</small><Sources sources={e.sources} /></article>)}</div>}

    {view === "states" && <div style={{ display: "grid", gap: 12 }}><div style={box}><h3>人物状态快照</h3>{selected.characterSnapshots.map((s) => <p key={s.id}><strong>{s.characterId}</strong> @ {s.chapterId}/{s.sceneId} · {s.location} · 身体 {s.body || "—"} · 情绪 {s.emotion || "—"} · 目标 {s.goal || "—"} · {s.confirmed ? "已确认" : "未确认"}</p>)}</div><div style={box}><h3>关系状态快照</h3>{selected.relationshipSnapshots.map((s) => <p key={s.id}><strong>{s.characterIds.join(" × ")}</strong> · {s.relationship} · 信任 {s.trust || "—"} · 权力 {s.power || "—"} · {s.confirmed ? "已确认" : "未确认"}</p>)}</div><div style={box}><h3>世界状态快照</h3>{selected.worldSnapshots.map((s) => <p key={s.id}><strong>{s.entityId}</strong> · {s.entityType} · {s.state} · {s.confirmed ? "已确认" : "未确认"}</p>)}</div></div>}

    {view === "knowledge" && <div style={box}><h3>知情矩阵</h3><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th align="left">信息</th><th align="left">读者</th><th align="left">角色</th><th>公开/秘密</th><th>来源</th></tr></thead><tbody>{selected.knowledgeStates.map((k) => <tr key={k.id}><td>{k.title}</td><td>{k.readerStatus}</td><td>{k.holders.map((h) => `${h.characterId}: ${h.status}${h.channel ? `（${h.channel}）` : "（渠道缺失）"}`).join("；")}</td><td align="center">{k.public ? "公开" : k.secret ? "秘密" : "未定"}</td><td>{k.sources.every((s) => s.valid) ? "有效" : "有失效"}</td></tr>)}</tbody></table></div>}

    {view === "threads" && <div style={{ display: "grid", gap: 12 }}><div style={box}><button style={primary} onClick={() => update((p) => { p.plotThreads.push(PlotThreadSchema.parse({ ...continuityBase("plot_thread"), title: "新剧情线" })); return p; })}>新增剧情线</button><button style={button} onClick={() => update((p) => { p.plotThreads.push(...createPlotThreadsFromPlans(draft.storyPlans)); return p; })}>从 Story Plan 创建</button></div>{selected.plotThreads.map((t) => <article style={box} key={t.id}><div style={{ ...row, justifyContent: "space-between" }}><input style={{ ...input, fontWeight: 700 }} value={t.title} onChange={(e) => update((p) => { const x = p.plotThreads.find((i) => i.id === t.id); if (x) x.title = e.target.value; return p; })} /><select style={input} value={t.status} onChange={(e) => update((p) => { const x = p.plotThreads.find((i) => i.id === t.id); if (x) x.status = e.target.value as typeof x.status; return p; })}>{["candidate", "active", "paused", "resolved", "abandoned", "deprecated"].map((s) => <option key={s}>{s}</option>)}</select></div><p>当前：{t.currentState || "未记录"}</p><p>下一节点：{t.nextNode || "未安排"} · 计划解决：{t.plannedResolutionLocation || "未安排"}</p><small>关联 Beat：{t.plotBeatIds.join("、") || "无"}</small></article>)}</div>}

    {view === "questions" && <div style={{ display: "grid", gap: 12 }}><button style={primary} onClick={() => update((p) => { p.openQuestions.push(OpenQuestionSchema.parse({ ...continuityBase("open_question"), question: "新未解决问题" })); return p; })}>新增问题</button>{selected.openQuestions.map((q) => <article style={box} key={q.id}><div style={row}><input style={{ ...input, flex: 1 }} value={q.question} onChange={(e) => update((p) => { const x = p.openQuestions.find((i) => i.id === q.id); if (x) x.question = e.target.value; return p; })} /><select style={input} value={q.status} onChange={(e) => update((p) => { const x = p.openQuestions.find((i) => i.id === q.id); if (x) x.status = e.target.value as typeof x.status; return p; })}>{["unanswered", "partially_answered", "answered", "intentionally_open", "deprecated"].map((s) => <option key={s}>{s}</option>)}</select></div><p>计划回答：{q.plannedAnswerLocation || "未安排"}</p></article>)}</div>}

    {view === "foreshadow" && <div style={{ display: "grid", gap: 12 }}><div style={box}><button style={primary} onClick={() => update((p) => { p.foreshadowThreads.push(ForeshadowThreadSchema.parse({ ...continuityBase("foreshadow_thread"), title: "新伏笔" })); return p; })}>新建伏笔</button><button style={button} onClick={() => update((p) => { p.foreshadowThreads.push(...importB2Foreshadows(draft.chapterPlanningProjects)); return p; })}>从章节与场景导入</button></div>{selected.foreshadowThreads.map((f) => <article style={box} key={f.id}><div style={{ ...row, justifyContent: "space-between" }}><strong>{f.title}</strong><span>{f.status}{f.overdue ? " · ⚠ 已过期" : ""}</span></div><p>{f.description}</p><p>计划回收：{f.plannedPayoffLocation || "未安排"}</p><ul>{f.events.sort((a, b) => a.order - b.order).map((e) => <li key={e.id}>{e.eventType} @ {e.chapterId || e.sceneId || "未定位"}：{e.description}</li>)}</ul></article>)}</div>}

    {view === "timeline" && <div style={box}><h3>全书时间线</h3>{[...selected.timeline.events].sort((a, b) => a.order - b.order).map((e) => <div key={e.id} style={{ borderLeft: `3px solid ${e.status === "conflicted" ? "var(--color-error)" : "var(--color-primary)"}`, padding: "6px 12px", margin: "8px 0" }}><strong>{e.date || (e.storyDay !== null ? `故事第 ${e.storyDay} 天` : `顺序 ${e.order}`)} · {e.title}</strong><div>{e.location} · {e.characterIds.join("、")} · {e.status}</div><small>{e.description}</small></div>)}</div>}

    {view === "summaries" && <div style={{ display: "grid", gap: 12 }}><div style={box}><button style={primary} onClick={() => update((p) => { for (const manuscript of draft.manuscripts) { const s = summarizeAcceptedManuscript(manuscript, p.sceneSummaries, p.chapterSummaries); p.sceneSummaries = [...p.sceneSummaries.filter((x) => x.sourceManuscriptId !== manuscript.id), ...s.scenes]; p.chapterSummaries = [...p.chapterSummaries.filter((x) => x.sourceManuscriptId !== manuscript.id), ...s.chapters]; for (const summary of s.scenes) for (const fact of summary.newFacts) if (!p.canonLedger.facts.some((item) => item.content === fact.content)) p.canonLedger.facts.push(createCanonFact({ title: fact.content.slice(0, 28), content: fact.content, status: "candidate", authority: 7, sources: [createContinuitySource("manuscript", summary.id, { sourceName: `场景摘要 ${summary.sceneId}`, version: summary.modifiedAt, authority: 7, classification: fact.classification === "fact" ? "project_fact" : "model_inference" })] })); } return p; })}>从当前采用正文生成摘要</button><p>摘要只产生候选事实和状态，不自动确认 Canon。正文 accepted 版本变化后旧摘要会标记 stale。</p></div><div style={box}><h3>章节摘要</h3>{selected.chapterSummaries.map((s) => <details key={s.id}><summary>{s.chapterId} · {s.stale ? "⚠ 过期" : "当前"}</summary><ul>{s.majorEvents.map((e, i) => <li key={i}>{e.classification}：{e.content}</li>)}</ul></details>)}</div><div style={box}><h3>场景摘要</h3>{selected.sceneSummaries.map((s) => <details key={s.id}><summary>{s.sceneId} · {s.stale ? "⚠ 过期" : "当前"}</summary><ul>{s.majorEvents.map((e, i) => <li key={i}>{e.classification}：{e.content}</li>)}</ul></details>)}</div></div>}

    {view === "drift" && <div style={{ display: "grid", gap: 12 }}>{selected.drifts.map((d) => <article key={d.id} style={box}><strong>{d.driftType}</strong> · {d.status}<p>{d.description}</p><p>影响：{d.impact || "待评估"}</p><p>建议：{d.recommendation}</p><div style={row}>{(["intentional", "accepted_manuscript", "plan_copy_created", "revision_task", "deferred"] as const).map((s) => <button key={s} style={button} onClick={() => update((p) => { const x = p.drifts.find((i) => i.id === d.id); if (x) x.status = s; return p; })}>{s}</button>)}</div></article>)}</div>}

    {view === "issues" && <div style={{ display: "grid", gap: 12 }}><div style={{ ...box, ...row }}><button style={primary} onClick={() => update((p) => { p.issues = validateContinuity(p); return p; })}>运行全书连续性检查</button><select style={input} value={issueSeverity} onChange={(e) => setIssueSeverity(e.target.value)}><option value="">全部严重程度</option>{severityOrder.map((s) => <option key={s}>{s}</option>)}</select><select style={input} value={issueType} onChange={(e) => setIssueType(e.target.value)}><option value="">全部类型</option>{[...new Set(selected.issues.map((i) => i.type))].map((s) => <option key={s}>{s}</option>)}</select></div>{visibleIssues.map((i) => <IssueCard key={i.id} issue={i} onResolve={(status) => update((p) => { const x = p.issues.find((v) => v.id === i.id); if (x) x.status = status; return p; })} />)}</div>}

    {view === "search" && <div style={{ display: "grid", gap: 12 }}><div style={{ ...box, ...row }}><input style={{ ...input, flex: 1 }} placeholder="搜索人物、地点、物品、事件和采用正文" value={query} onChange={(e) => setQuery(e.target.value)} /><span>本地全文与元数据索引 · {entityResults.length} 条</span></div>{entityResults.map((e) => <article key={e.id} style={box}><strong>{e.name}</strong> · {e.entityType}<p>{e.description.slice(0, 500)}</p><p>来源位置：{e.sources.map((s) => `${s.sourceType}:${s.sourceId}`).join("；")}</p></article>)}</div>}

    {view === "progress" && <div style={{ display: "grid", gap: 12 }}><div style={row}><Stat label="正式总字数" value={selected.writingProgress.totalWords} /><Stat label="规划完成率" value={`${selected.writingProgress.planningCompletion}%`} /><Stat label="初稿完成率" value={`${selected.writingProgress.draftCompletion}%`} /><Stat label="修订完成率" value={`${selected.writingProgress.revisionCompletion}%`} /></div><div style={box}><h3>章节</h3>{selected.writingProgress.chapterWords.map((x) => <p key={x.id}>{x.name} · {x.words} 字 · {x.status}</p>)}</div><div style={box}><h3>场景</h3>{selected.writingProgress.sceneWords.map((x) => <p key={x.id}>{x.name} · {x.words} 字 · {x.status}</p>)}<small>未接受的 alternative / incomplete 草稿不计入正式完成度。</small></div></div>}

    {view === "next" && <div style={{ display: "grid", gap: 12 }}><div style={box}><button style={primary} onClick={() => update((p) => { p.contextPackages.push(buildNextChapterContextPackage(p, draft.chapterPlanningProjects[0] ?? null)); return p; })}>生成下一章上下文包</button><p>可以编辑和锁定；发送只更新包状态，不自动修改章节与场景或正文。</p></div>{selected.contextPackages.map((c) => <article key={c.id} style={box}><div style={{ ...row, justifyContent: "space-between" }}><strong>章节 {c.chapterId || "未选择"}</strong><span>{c.status}</span></div><label>目标<textarea style={{ ...input, width: "100%", boxSizing: "border-box" }} value={c.chapterGoal} disabled={c.lockedFields.includes("chapterGoal")} onChange={(e) => update((p) => { const x = p.contextPackages.find((i) => i.id === c.id); if (x) x.chapterGoal = e.target.value; return p; })} /></label><p>前章结束：{c.previousEndingState}</p><p>当前剧情线：{c.plotThreadIds.join("、")}</p><p>未完成行动：{c.unfinishedActions.join("；")}</p><p>本章伏笔/回收：{c.foreshadowIds.join("、")} / {c.payoffIds.join("、")}</p><p>禁止提前：{c.prohibitedEarlyEvents.join("；")}</p><p>视角规则：{c.povRules.join("；")}</p><p>连续性风险：{c.continuityRisks.join("；")}</p><div style={row}><button style={button} onClick={() => update((p) => { const x = p.contextPackages.find((i) => i.id === c.id); if (x) { x.status = x.status === "locked" ? "draft" : "locked"; x.lockedFields = x.status === "locked" ? ["chapterGoal", "previousEndingState", "prohibitedEarlyEvents"] : []; } return p; })}>{c.status === "locked" ? "解锁" : "锁定"}</button><button style={button} onClick={() => update((p) => { const x = p.contextPackages.find((i) => i.id === c.id); if (x) x.status = "sent_to_b2"; return p; })}>发送到章节与场景</button><button style={button} onClick={() => update((p) => { const x = p.contextPackages.find((i) => i.id === c.id); if (x) x.status = "sent_to_b3"; return p; })}>发送到正文写作</button></div></article>)}</div>}
  </section>;
}

function IssueCard({ issue, onResolve }: { issue: ContinuityIssue; onResolve(status: ContinuityIssue["status"]): void }) {
  const color = issue.severity === "critical" ? "var(--color-error)" : issue.severity === "major" ? "var(--color-warning)" : "var(--color-primary)";
  return <article style={{ ...box, borderLeft: `5px solid ${color}` }}><div style={{ ...row, justifyContent: "space-between" }}><strong>{issue.title}</strong><span>{issue.severity} · {issue.confidence} · {issue.heuristic ? "启发式" : "确定规则"}</span></div><p>{issue.rationale}</p><p><strong>最小修复：</strong>{issue.minimumRevision}</p><p><strong>副作用：</strong>{issue.sideEffects.join("；") || "未评估"}</p><Sources sources={issue.sources} /><div style={row}>{(["accepted", "intentional", "fixed", "false_positive", "deferred", "retcon_required"] as const).map((s) => <button key={s} style={button} onClick={() => onResolve(s)}>{s}</button>)}</div></article>;
}
