"use client";
import { useMemo, useState } from "react";
import type { CharacterCardV2 } from "@/domain/character-card";
import type { Lorebook } from "@/domain/lorebook";
import { createEmptyAnalysisProject, createEmptyBranch, type AnalysisInput, type AnalysisReport, type PlotAnalysisProject } from "@/domain/plot-analysis";
import type { ProviderType } from "@/providers/types";
import { buildAnalysisContext, AUTHORITY_LABELS, getCurrentSourceVersions } from "@/services/analysis-context-builder";
import { analysisFilename, downloadText, exportAnalysisJSON, exportAnalysisMarkdown } from "@/services/analysis-export";
import { usePwaRuntime } from "@/components/pwa/PwaRuntime";

interface Props { projects: PlotAnalysisProject[]; selected: PlotAnalysisProject | null; characterCard: CharacterCardV2; lorebooks: Lorebook[];
  provider: ProviderType; model: string; onAdd: (p: PlotAnalysisProject) => void; onUpdate: (p: PlotAnalysisProject) => void; onDelete: (id: string) => void;
  onSelect: (id: string | null) => void; onSaveReport: (id: string, r: AnalysisReport) => void; onAddNote: (n: string) => void; onProvider: (p: ProviderType, m: string) => void; }
const MODELS: Record<ProviderType, string[]> = { mock: ["mock-model"], openai: ["gpt-4o-mini", "gpt-4.1"], anthropic: ["claude-haiku-4-5-20251001", "claude-sonnet-5-20251001"] };
const SEVERITIES = ["all", "critical", "major", "moderate", "minor", "note"];
const CATEGORIES = ["all", "hard_contradiction", "causal_gap", "motivation_gap", "character_mismatch", "information_violation", "capability_violation", "world_rule_violation", "continuity_error", "relationship_jump", "tone_mismatch", "pacing_risk", "reader_clarity_risk", "missing_evidence", "opportunity"];

export function PlotAnalysisWorkspace(props: Props) {
  const { isOnline } = usePwaRuntime();
  const p = props.selected; const [report, setReport] = useState<AnalysisReport | null>(null); const [loading, setLoading] = useState(false); const [controller, setController] = useState<AbortController | null>(null);
  const [message, setMessage] = useState(""); const [severity, setSeverity] = useState("all"); const [category, setCategory] = useState("all"); const [character, setCharacter] = useState("all");
  const context = useMemo(() => p ? buildAnalysisContext({ project: p, characterCard: props.characterCard, lorebooks: props.lorebooks }) : null, [p, props.characterCard, props.lorebooks]);
  const update = (next: PlotAnalysisProject) => props.onUpdate({ ...next, title: next.input.title, proposal: { ...next.proposal, occurredPlot: next.input.occurredPlot, proposedPlot: next.input.proposedPlot, plotGoal: next.input.plotGoal, branches: next.input.branches }, modifiedAt: new Date().toISOString() });
  const input = <K extends keyof AnalysisInput>(key: K, value: AnalysisInput[K]) => { if (p) update({ ...p, input: { ...p.input, [key]: value } }); };
  const currentReport = report || p?.reports.at(-1) || null;
  const filtered = currentReport?.issues.filter(issue => (severity === "all" || issue.severity === severity) && (category === "all" || issue.category === category) && (character === "all" || issue.characters.includes(character))) || [];
  const outdated = useMemo(() => { if (!currentReport) return false; const versions = getCurrentSourceVersions(props.characterCard, props.lorebooks);
    return Object.entries(currentReport.sourceVersions).some(([key, version]) => versions[key] !== version); }, [currentReport, props.characterCard, props.lorebooks]);

  const run = async () => { if (!p) return; if (!isOnline) { setMessage("当前离线，剧情分析已暂停；输入和历史报告仍可编辑查看。"); return; } const abort = new AbortController(); setController(abort); setLoading(true); setMessage(""); try {
    const response = await fetch("/api/analyze-plot", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ project: p, characterCard: props.characterCard, lorebooks: props.lorebooks, provider: props.provider, model: props.model }), signal: abort.signal });
    const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || `请求失败 (${response.status})`); setReport(result.data); setMessage("分析完成。请确认后保存报告；源剧情、角色卡和世界书未被修改。");
  } catch (error) { setMessage(abort.signal.aborted ? "分析已取消。" : `分析失败：${(error as Error).message}`); } finally { setLoading(false); setController(null); } };

  if (!p) return <div className="card empty-state"><h2>剧情合理性与人物契合度分析</h2><p>创建一个分析项目，原始剧情输入不会被模型结果覆盖。</p><button className="btn-primary" onClick={() => props.onAdd(createEmptyAnalysisProject())}>新建剧情分析</button></div>;
  return <div className="analysis-layout">
    <section className="card analysis-input"><div className="card-header"><span>🎬 分析输入</span><div><select value={p.id} onChange={e => props.onSelect(e.target.value)}>{props.projects.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select> <button className="btn-secondary" onClick={() => props.onAdd(createEmptyAnalysisProject())}>新建</button> <button className="btn-danger" onClick={() => window.confirm("删除该分析项目和本地报告？角色卡和世界书不会被删除。") && props.onDelete(p.id)}>删除</button></div></div>
      <label className="analysis-field">分析标题<input value={p.input.title} onChange={e => input("title", e.target.value)} /></label>
      <label className="analysis-field">已发生剧情<textarea value={p.input.occurredPlot} onChange={e => input("occurredPlot", e.target.value)} /></label>
      <label className="analysis-field">待分析剧情<textarea value={p.input.proposedPlot} onChange={e => input("proposedPlot", e.target.value)} /></label>
      <label className="analysis-field">剧情目标<input value={p.input.plotGoal} onChange={e => input("plotGoal", e.target.value)} /></label>
      <div className="compact-grid"><label>当前时间<input value={p.input.currentTime} onChange={e => input("currentTime", e.target.value)} /></label><label>当前地点<input value={p.input.currentPlace} onChange={e => input("currentPlace", e.target.value)} /></label></div>
      <label className="analysis-field">角色当前信息状态<textarea value={p.input.characterKnowledge} onChange={e => input("characterKnowledge", e.target.value)} /></label>
      <label className="analysis-field">角色当前情绪<textarea value={p.input.characterEmotions} onChange={e => input("characterEmotions", e.target.value)} /></label>
      <label className="analysis-field">当前关系状态<textarea value={p.input.relationshipState} onChange={e => input("relationshipState", e.target.value)} /></label>
      <label className="analysis-field">必须保留的结果<textarea value={p.input.requiredOutcomes} onChange={e => input("requiredOutcomes", e.target.value)} /></label>
      <label className="analysis-field">不可修改设定<textarea value={p.input.immutableSettings} onChange={e => input("immutableSettings", e.target.value)} /></label>
      <label className="analysis-field">允许模型补充的空白<textarea value={p.input.fillableGaps} onChange={e => input("fillableGaps", e.target.value)} /></label>
      <label className="analysis-field">用户备注<textarea value={p.input.userNotes} onChange={e => input("userNotes", e.target.value)} /></label>
      <fieldset><legend>分析侧重点</legend>{(["comprehensive", "causality", "character_fit", "relationship", "world_consistency", "continuity", "drama", "branch_comparison"] as const).map(f => <label key={f}><input type="checkbox" checked={p.input.focuses.includes(f)} onChange={e => input("focuses", e.target.checked ? [...p.input.focuses, f] : p.input.focuses.filter(x => x !== f))} /> {f}</label>)}</fieldset>
      <div className="card-header"><span>备选分支（最多 3 个）</span><button className="btn-secondary" disabled={p.input.branches.length >= 3} onClick={() => input("branches", [...p.input.branches, createEmptyBranch(p.input.branches.length)])}>添加分支</button></div>
      {p.input.branches.map((branch, index) => <div className="branch-box" key={branch.id}><input value={branch.name} onChange={e => input("branches", p.input.branches.map(x => x.id === branch.id ? { ...x, name: e.target.value } : x))} /><textarea value={branch.description} placeholder="剧情描述" onChange={e => input("branches", p.input.branches.map(x => x.id === branch.id ? { ...x, description: e.target.value } : x))} /><input value={branch.expectedEffect} placeholder="预期效果" onChange={e => input("branches", p.input.branches.map(x => x.id === branch.id ? { ...x, expectedEffect: e.target.value } : x))} /><input value={branch.acceptableChanges} placeholder="可接受修改范围" onChange={e => input("branches", p.input.branches.map(x => x.id === branch.id ? { ...x, acceptableChanges: e.target.value } : x))} /><div className="button-row"><button className="btn-secondary" disabled={p.input.branches.length >= 3} onClick={() => input("branches", [...p.input.branches, { ...branch, id: createEmptyBranch(index).id, name: `${branch.name} 副本` }])}>复制</button><button className="btn-danger" onClick={() => input("branches", p.input.branches.filter(x => x.id !== branch.id))}>删除</button></div></div>)}
    </section>

    <section className="card analysis-context"><div className="card-header"><span>📚 上下文资料</span><span>{context?.estimatedTokens || 0}/{p.tokenBudget} tokens</span></div>
      <label><input type="checkbox" checked={p.selectedCharacterIds.includes(props.characterCard.data.name || "current-character")} onChange={e => update({ ...p, selectedCharacterIds: e.target.checked ? [props.characterCard.data.name || "current-character"] : [] })} /> 当前角色卡：{props.characterCard.data.name || "未命名"}</label>
      <div><strong>参与角色</strong><input value={p.input.participatingCharacters.join("，")} onChange={e => input("participatingCharacters", e.target.value.split(/[,，]/).map(x => x.trim()).filter(Boolean))} placeholder="用逗号分隔" /></div>
      {props.lorebooks.map(book => <div key={book.id} className="source-book"><label><input type="checkbox" checked={p.selectedLorebookIds.includes(book.id)} onChange={e => update({ ...p, selectedLorebookIds: e.target.checked ? [...p.selectedLorebookIds, book.id] : p.selectedLorebookIds.filter(id => id !== book.id) })} /> {book.name}</label>{p.selectedLorebookIds.includes(book.id) && book.entries.map(entry => <label key={entry.id} className="source-entry">{entry.name || "未命名"}<select value={p.manualIncludedEntryIds.includes(entry.id) ? "include" : p.manualExcludedEntryIds.includes(entry.id) ? "exclude" : "auto"} onChange={e => { const v = e.target.value; update({ ...p, manualIncludedEntryIds: v === "include" ? [...p.manualIncludedEntryIds.filter(id => id !== entry.id), entry.id] : p.manualIncludedEntryIds.filter(id => id !== entry.id), manualExcludedEntryIds: v === "exclude" ? [...p.manualExcludedEntryIds.filter(id => id !== entry.id), entry.id] : p.manualExcludedEntryIds.filter(id => id !== entry.id) }); }}><option value="auto">自动筛选</option><option value="include">手动包含</option><option value="exclude">排除</option></select></label>)}</div>)}
      <label>Token 预算<input type="number" min="256" value={p.tokenBudget} onChange={e => update({ ...p, tokenBudget: Math.max(256, Number(e.target.value)) })} /></label>
      {context?.truncated && <div className="warning-line">上下文已按权威等级、手动选择和相关性裁剪。</div>}
      <details open><summary>预计发送给模型的上下文清单</summary>{context?.sources.map(source => <div className={`context-row ${source.included ? "included" : "excluded"}`} key={source.id}><strong>{source.included ? "✓" : "×"} {source.name} / {source.field}</strong><span>{AUTHORITY_LABELS[source.authority]} · {source.classification} · ~{source.tokenEstimate} tokens</span><small>{source.inclusionReason}</small><p>{source.content.slice(0, 180)}</p></div>)}</details>
      <div className="provider-row"><select value={props.provider} onChange={e => { const next = e.target.value as ProviderType; props.onProvider(next, MODELS[next][0]); }}><option value="mock">Mock</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select><select value={props.model} onChange={e => props.onProvider(props.provider, e.target.value)}>{MODELS[props.provider].map(m => <option key={m}>{m}</option>)}</select>{loading ? <button className="btn-danger" onClick={() => controller?.abort()}>取消</button> : <button className="btn-primary" disabled={!p.input.proposedPlot.trim() || !isOnline} onClick={run}>开始分析</button>}</div>{!isOnline && <div className="notice">离线状态下不会提交分析请求。</div>}{message && <div className="notice">{message}</div>}
    </section>

    {currentReport && <section className="card full-width analysis-report"><div className="card-header"><span>📊 分析结果</span><div>{outdated && <span className="tag warning">基于旧版本项目资料</span>} <button className="btn-primary" onClick={() => { props.onSaveReport(p.id, currentReport); setMessage("报告已确认并保存。 "); }}>确认并保存</button><button className="btn-secondary" onClick={() => downloadText(exportAnalysisMarkdown(currentReport), analysisFilename(currentReport, "md"), "text/markdown")}>Markdown</button><button className="btn-secondary" onClick={() => downloadText(exportAnalysisJSON(currentReport), analysisFilename(currentReport, "json"), "application/json")}>JSON</button></div></div>
      <h2>{currentReport.summary.oneLineConclusion}</h2><div className="summary-grid"><div><strong>总体可行性</strong><p>{currentReport.summary.feasibility}</p></div><div><strong>主要优点</strong><p>{currentReport.summary.strengths.join("；")}</p></div><div><strong>最低成本修复</strong><p>{currentReport.summary.lowestCostFix}</p></div><div><strong>信息缺口</strong><p>{currentReport.summary.informationGaps.join("；")}</p></div></div>
      <h3>维度评分 <small>（{currentReport.scoringVersion}；critical 问题单独显示，不被平均分掩盖）</small></h3><div className="score-grid">{currentReport.scores.map(s => <div key={s.dimension}><strong>{s.dimension}</strong><b>{s.score}</b><small>{s.rationale}</small></div>)}</div>
      <h3>问题报告</h3><div className="filter-row"><select value={severity} onChange={e => setSeverity(e.target.value)}>{SEVERITIES.map(x => <option key={x}>{x}</option>)}</select><select value={category} onChange={e => setCategory(e.target.value)}>{CATEGORIES.map(x => <option key={x}>{x}</option>)}</select><select value={character} onChange={e => setCharacter(e.target.value)}><option>all</option>{p.input.participatingCharacters.map(x => <option key={x}>{x}</option>)}</select></div>
      {filtered.map(issue => <article className={`analysis-issue ${issue.severity}`} key={issue.id}><header><strong>{issue.title}</strong><span>{issue.category} · {issue.severity} · {issue.confidence}{issue.is_hard_contradiction ? " · 硬冲突" : ""}</span></header><p>{issue.conclusion}</p><details><summary>证据与简洁推理摘要</summary><p>{issue.evidence.join("；")}</p><p>{issue.reasoning_summary}</p><p>缺失信息：{issue.missing_information.join("；") || "无"}</p>{issue.source_references.map((ref, i) => <div className={ref.valid ? "valid-ref" : "invalid-ref"} key={i}>{ref.valid ? "有效" : "无效"}｜{ref.source_name}/{ref.field_or_entry}｜{ref.excerpt}{ref.inference ? `｜推断(${ref.confidence})` : ""}</div>)}</details><div className="revision"><strong>最小修改：</strong>{issue.minimum_revision}<br/><strong>副作用：</strong>{issue.side_effects.join("；")}</div><div className="button-row"><button className="btn-secondary" onClick={() => navigator.clipboard.writeText(issue.minimum_revision)}>复制建议</button><button className="btn-secondary" onClick={() => props.onAddNote(`${issue.title}：${issue.minimum_revision}`)}>保存为项目备注</button></div></article>)}
      <div className="report-grid"><div><h3>人物逐个分析</h3>{currentReport.characterFits.map(x => <p key={x.character}><strong>{x.character} {x.score}/100</strong>：{x.fitConclusion}<br/>所需触发：{x.requiredTrigger || "未明确"}</p>)}</div><div><h3>因果链</h3><p>{currentReport.causality.conclusion}</p><p>步骤：{currentReport.causality.intermediateSteps.join(" → ")}</p></div><div><h3>情感与关系</h3><p>阶段：{currentReport.relationship.currentStage}</p><p>缺少铺垫：{currentReport.relationship.missingSetup}</p></div><div><h3>世界观与连续性</h3><p>{currentReport.continuity.conclusion}</p><p>{currentReport.continuity.timeAndPlace}</p></div></div>
      {currentReport.branchComparison && <><h3>分支比较</h3><div className="branch-comparison">{currentReport.branchComparison.branches.map(b => <div key={b.branchId}><strong>#{b.rank} {b.branchName}</strong><p>{b.oneLineConclusion}</p><p>人物 {b.characterFit} / 因果 {b.causalCompleteness}</p><small>铺垫：{b.requiredSetup.join("；")}<br/>后续约束：{b.futureConstraints.join("；")}</small></div>)}</div><p>{currentReport.branchComparison.recommendationSummary}</p></>}
      <h3>引用资料与元数据</h3>{currentReport.invalidReferenceWarnings.map(w => <div className="warning-line" key={w}>{w}</div>)}<div className="reference-list">{currentReport.referencedSources.map((ref, i) => <div key={i} className={ref.valid ? "valid-ref" : "invalid-ref"}>{ref.valid ? "有效" : "无效"}｜{ref.source_type}｜{ref.source_name}/{ref.field_or_entry}｜{ref.excerpt}</div>)}</div><p className="field-hint">{currentReport.provider}/{currentReport.model} · {currentReport.promptVersion} · {currentReport.createdAt} · 状态 {currentReport.status}</p>
    </section>}
  </div>;
}
