"use client";
import { useMemo, useState } from "react";
import type { ProjectDraft } from "@/domain/project-draft";
import type { AppView } from "./ui/navigation";
import { queryVisualReadModels } from "@/services/visual-read-model";
import { exportVisualCsv, exportVisualJson, exportVisualPng, exportVisualSvg } from "@/services/visual-export";

type Tab = "overview" | "relationships" | "timeline" | "threads" | "foreshadow" | "knowledge" | "pacing" | "presence";
const TABS: Array<[Tab, string]> = [["overview", "概览"], ["relationships", "关系图"], ["timeline", "时间线"], ["threads", "剧情线"], ["foreshadow", "伏笔"], ["knowledge", "知情矩阵"], ["pacing", "章节节奏"], ["presence", "角色出场"]];
const download = (content: BlobPart, name: string, type: string) => { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); };
export function VisualWorkspace({ draft, onNavigate }: { draft: ProjectDraft; onNavigate(view: AppView): void }) {
  const [tab, setTab] = useState<Tab>("overview"); const [status, setStatus] = useState(""); const [character, setCharacter] = useState(""); const [narrative, setNarrative] = useState(false); const [page, setPage] = useState(0);
  const model = useMemo(() => queryVisualReadModels(draft, { maxNodes: 500, pageSize: 50 }), [draft.savedAt, draft.continuityProjects, draft.chapterPlanningProjects, draft.manuscripts]);
  const rawRows: any[] = tab === "relationships" ? model.views.relationshipGraph.edges : tab === "timeline" ? (narrative ? model.views.timeline.narrativeOrder : model.views.timeline.actualOrder) : tab === "threads" ? model.views.plotThread.items : tab === "foreshadow" ? model.views.foreshadow.items : tab === "knowledge" ? model.views.knowledgeMatrix.rows : tab === "pacing" ? model.views.pacingSeries.points : tab === "presence" ? model.views.characterPresence.characters : [];
  const rows = rawRows.filter((item) => (!status || item.state === status || item.status === status) && (!character || item.characterId === character || item.fromCharacterId === character || item.toCharacterId === character || item.characterIds?.includes(character))).slice(page * 50, page * 50 + 50);
  const title = TABS.find(([id]) => id === tab)?.[1] ?? "概览"; const svg = exportVisualSvg(title, rows); const characters = model.views.characterPresence.characters;
  const jump = (item: any) => { if (item.jump?.view) onNavigate(item.jump.view as AppView); };
  const exportRows = (kind: "svg" | "png" | "csv" | "json") => { if (kind === "svg") download(svg, `${title}.svg`, "image/svg+xml"); else if (kind === "csv") download(exportVisualCsv(rows), `${title}.csv`, "text/csv;charset=utf-8"); else if (kind === "json") download(exportVisualJson(rows), `${title}.json`, "application/json"); else void exportVisualPng(svg).then((blob) => download(blob, `${title}.png`, "image/png")); };
  return <section className="visual-workspace" data-mobile-single-view="true"><div className="card"><div className="card-header"><span>可视化工作台</span><span className="field-hint">只读视图 · {model.generatedAt}</span></div><div className="visual-tabs" role="tablist">{TABS.map(([id, label]) => <button role="tab" aria-selected={tab === id} className={`tab ${tab === id ? "active" : ""}`} key={id} onClick={() => { setTab(id); setPage(0); }}>{label}</button>)}</div></div>
    {tab === "overview" ? <div className="visual-overview">{[["关系变化", model.views.relationshipGraph.edges.length], ["时间事件", model.views.timeline.actualOrder.length], ["剧情线", model.views.plotThread.items.length], ["伏笔", model.views.foreshadow.items.length], ["知情项", model.views.knowledgeMatrix.rows.length], ["章节节奏", model.views.pacingSeries.points.length], ["出场角色", model.views.characterPresence.characters.length]].map(([label, count]) => <article className="card" key={label}><strong>{label}</strong><span className="visual-count">{count}</span></article>)}</div> : <><details className="card visual-filters" open><summary>筛选与导出</summary><div className="form-grid"><label>角色<select value={character} onChange={(e) => setCharacter(e.target.value)}><option value="">全部角色</option>{characters.map((item) => <option key={item.id} value={item.characterId}>{item.title}</option>)}</select></label><label>状态<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">全部状态</option><option value="confirmed">确认</option><option value="candidate">候选</option><option value="conflict">冲突</option></select></label>{tab === "timeline" && <label className="check-row"><input type="checkbox" checked={narrative} onChange={(e) => setNarrative(e.target.checked)} />正文叙事顺序</label>}</div><div className="button-row">{(["png", "svg", "csv", "json"] as const).map((kind) => <button className="btn-secondary" key={kind} onClick={() => exportRows(kind)}>导出 {kind.toUpperCase()}</button>)}</div></details><div className="card visual-chart" aria-label={`${title}图表`} dangerouslySetInnerHTML={{ __html: svg }} /><div className="card" aria-label="可访问列表视图"><div className="card-header"><span>{title}列表</span><span>第 {page + 1} 页</span></div><div className="visual-table-wrap"><table><thead><tr><th>名称</th><th>状态</th><th>章节</th><th>详情</th><th>来源</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td>{item.title}</td><td>{item.conflict ? "冲突" : item.stale ? "过期" : item.state === "confirmed" ? "确认" : "候选"}</td><td>{item.chapterId || "—"}</td><td>{item.relationship || item.currentState || item.location || item.status}</td><td><button className="btn-secondary" onClick={() => jump(item)}>查看来源</button></td></tr>)}</tbody></table></div><div className="button-row"><button disabled={page === 0} onClick={() => setPage((x) => x - 1)}>上一页</button><button disabled={(page + 1) * 50 >= rawRows.length} onClick={() => setPage((x) => x + 1)}>下一页</button></div></div></>}
  </section>;
}
